swagger: '2.0'
info:
  title: AirPlatform-AirEngine-FileTransfer API（BaseURL:192.168.2.156:31153/api/v1/airengine/file_transfer/）
  description: These APIs provide services for AirPlatform-AirEngine FileTransfer backend project. 引擎中负责文件上传下载的相关功能
  version: 1.0.0
host: 192.168.2.156:31153
schemes:
  - http
basePath: /api/v1/airengine/file_transfer/
tags:
  - name: "Upload"
    description: 文件上传
  - name: "Download"
    description: 文件下载
  - name: "Static"
    description: 静态文件
paths:
  /upload/:
    get:
      summary: 返回所有上传文件的信息
      description: 依据token确定用户的管理范围，返回管理范围内的经过组织和排序的上传文件信息列表
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: page_size
          in: query
          description: 显示页大小
          required: true
          type: integer
        - name: page_num
          in: query
          description: 显示页的编号
          required: true
          type: integer
        - name: rules
          in: query
          description: 排序筛选规则对应的字符串表示，是一个字典，包含以下几个key： sort_col（排序列名的列表），sort_order（排序列对应的排序方法列表：DESC/ASC），partial_match_col（执行部分匹配的列名列表），partial_match_input（执行部分匹配查找的列名对应的数值内容的列表），剩余的key对应范围匹配，使用列名作为key，数值存放了查找的范围，一般用于存放日期示例：{"sort_col":["name", "id"],"sort_order":["ASC", "DESC"], "partial_match_col":["name", "realname"], "partial_match_input":["test", "张2"], "upload_time":["2018-06-26 14:59:59", "2018-06-26 14:59:59"]
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 上传文件信息列表
          schema:
            $ref: "#/definitions/UploadFileInfoList"
        '500':
          description: Internal Error
    post:
      summary: 添加新的文件上传任务
      description: 给出文件的基本信息，交由后台创建文件上传记录
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file_size
          in: formData
          description: 文件大小，单位字节
          required: true
          type: integer
        - name: origin_file_name
          in: formData
          description: 文件的原文件名称
          required: true
          type: string
        - name: test_file
          in: formData
          description: 用于测试网速的文件（也可以通过单独的接口完成网速测试，然后在第二步主动设置预测的网速）
          type: file
        - name: usage_tag
          in: formData
          description: 查询时给出对应的使用标签
          required: true
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 状态码
          schema:
            $ref: "#/definitions/UploadFileFeedback"
        '500':
          description: Internal Error
    delete:
      summary: 删除多个已经上传的文件缓存
      description: 按照给定ID列表删除单个或者多个上传文件缓存
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: file_ids
          in: query
          description: 多个上传文件ID列表的json字串
          type: string
        - name: user_ids
          in: query
          description: 多个用户ID列表的json字串，按照用户删除对应文件记录和缓存
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 状态码
          schema:
            $ref: '#/definitions/StatusCode'
        '500':
          description: Internal Error
  /upload/test:
    post:
      summary: 上传速度测试
      description: 提供给前端进行上传网络带宽测试
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: test_file
          in: formData
          description: 用于测试网速的文件
          type: file
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 状态码
          schema:
            $ref: "#/definitions/StatusCode"
        '500':
          description: Internal Error
  /upload/update_standard_md5:
    post:
      summary: 分块上传-更新标准MD5
      description: 更新标准的MD5采样结果，测试网速，并获取随机采样MD5方法以及分块大小
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file_id
          in: formData
          description: 上传文件的ID
          required: true
          type: integer
        - name: standard_md5
          in: formData
          description: 文件的标准MD5结果
          type: string
          required: true
        - name: request_time_stamp
          in: formData
          description: 请求开始的时间戳，单位毫秒
          type: integer
        - name: test_file
          in: formData
          description: 用于测试网速的文件
          type: file
        - name: network_speed
          in: formData
          description: 网速，单位字节/秒
          type: integer
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 状态码
          schema:
            $ref: "#/definitions/UploadFileFeedback"
        '500':
          description: Internal Error
  /upload/update_random_md5:
    post:
      summary: 分块上传-更新随机MD5
      description: 更新随机MD5采样的结果，由后台创建文件块列表
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file_id
          in: formData
          description: 上传文件的ID
          required: true
          type: integer
        - name: random_md5
          in: formData
          description: 文件的随机MD5采样结果
          type: string
          required: true
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 状态码
          schema:
            $ref: "#/definitions/UploadFileFeedback"
        '500':
          description: Internal Error
  /upload/upload_chunk:
    post:
      summary: 分块上传-上传文件块
      description: 上传一个文件块（也可能不上传），并领取新的上传任务
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file_id
          in: formData
          description: 上传文件的ID
          required: true
          type: integer
        - name: request_time_stamp
          in: formData
          description: 请求开始的时间戳，单位毫秒
          required: true
          type: integer
        - name: chunk_id
          in: formData
          description: 上传文件块的ID
          required: true
          type: integer        
        - name: chunk_file
          in: formData
          description: 上传的文件块文件
          required: true
          type: file
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 状态码
          schema:
            $ref: "#/definitions/UploadChunkFeedback"
        '500':
          description: Internal Error
  /upload/get/{file_id}:
    get:
      summary: 返回单个上传文件的信息
      description: 依据token确定用户的管理范围，返回管理范围内的经过组织和排序的上传文件的信息
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: file_id
          in: path
          description: 上传文件ID
          required: true
          type: integer
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 上传文件信息
          schema:
            $ref: "#/definitions/UploadFileInfoSingle"
        '500':
          description: Internal Error
  /upload/get:
    get:
      summary: 返回多个匹配的上传文件的详细信息
      description: 依据token确定用户的管理范围，返回管理范围内的经过组织和排序的上传文件详细信息列表
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: file_ids
          in: query
          description: 上传文件ID列表的json字串
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Upload
      responses:
        '200':
          description: 上传文件信息
          schema:
            $ref: "#/definitions/UploadFileInfoList"
        '500':
          description: Internal Error
  /download/:
    get:
      summary: 返回所有下载文件的信息
      description: 依据token确定用户的管理范围，返回管理范围内的经过组织和排序的下载文件信息列表
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: page_size
          in: query
          description: 显示页大小
          required: true
          type: integer
        - name: page_num
          in: query
          description: 显示页的编号
          required: true
          type: integer
        - name: rules
          in: query
          description: 排序筛选规则对应的字符串表示，是一个字典，包含以下几个key： sort_col（排序列名的列表），sort_order（排序列对应的排序方法列表：DESC/ASC），partial_match_col（执行部分匹配的列名列表），partial_match_input（执行部分匹配查找的列名对应的数值内容的列表），剩余的key对应范围匹配，使用列名作为key，数值存放了查找的范围，一般用于存放日期示例：{"sort_col":["name", "id"],"sort_order":["ASC", "DESC"], "partial_match_col":["name", "realname"], "partial_match_input":["test", "张2"], "upload_time":["2018-06-26 14:59:59", "2018-06-26 14:59:59"]
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Download
      responses:
        '200':
          description: 下载文件信息列表
          schema:
            $ref: "#/definitions/DownloadFileInfoList"
        '500':
          description: Internal Error
    post:
      summary: 添加新的文件下载链接
      description: 给出文件的基本信息，交由后台创建文件需要下载文件到静态文件的链接，自动转换为静态文件下载地址
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: src_file_path
          in: formData
          description: 目标下载文件的服务器绝对路径
          required: true
          type: string
        - name: service_id
          in: formData
          description: 创建下载的后台服务ID
          required: true
          type: integer
        - name: download_file_name
          in: formData
          description: 下载时文件对应的名称，如果没有给出则按照源文件名称创建下载连接
          required: false
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Download
      responses:
        '200':
          description: 状态码
          schema:
            $ref: "#/definitions/DownloadFileInfoSingle"
        '500':
          description: Internal Error
    delete:
      summary: 删除多个下载文件缓存
      description: 按照给定ID列表删除单个或者多个下载文件缓存
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: file_ids
          in: query
          description: 多个下载文件ID列表的json字串
          type: string
        - name: user_ids
          in: query
          description: 多个用户ID列表的json字串，按照用户删除文件缓存
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Download
      responses:
        '200':
          description: 状态码
          schema:
            $ref: '#/definitions/StatusCode'
        '500':
          description: Internal Error
  /download/get/{file_id}:
    get:
      summary: 返回单个下载文件的信息
      description: 依据token确定用户的管理范围，返回管理范围内的经过组织和排序的下载文件的信息
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: file_id
          in: path
          description: 下载文件ID
          required: true
          type: integer
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Download
      responses:
        '200':
          description: 下载文件信息
          schema:
            $ref: "#/definitions/DownloadFileInfoSingle"
        '500':
          description: Internal Error
  /download/get:
    get:
      summary: 返回多个匹配的下载文件的详细信息
      description: 依据token确定用户的管理范围，返回管理范围内的经过组织和排序的下载文件详细信息列表
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: file_ids
          in: query
          description: 下载文件ID列表的json字串
          type: string
        - name: token
          in: header
          description: 用户token
          required: true
          type: string
      tags:
        - Download
      responses:
        '200':
          description: 下载文件信息
          schema:
            $ref: "#/definitions/DownloadFileInfoList"
        '500':
          description: Internal Error
  /static/{file_path}:
    get:
      summary: 下载静态文件
      description: URL中的路径下载文件
      consumes:
        - application/json
      produces:
        - apllication/json
      parameters:
        - name: file_path
          in: path
          description: 静态文件相对路径（不包含static）
          required: true
          type: string
      tags:
        - Static
      responses:
        '200':
          description: 返回下载文件的二进制流
        '500':
          description: Internal Error

definitions:
  StatusCode:
    type: object
    properties:
      code:
        type: integer
        description: 状态码（成功为0，否则为非0）
      message:
        type: string
        description: 状态信息
  UploadFileInfo:
    type: object
    properties:
      id:
        type: integer
        description: 文件ID
      file_size:
        type: integer
        description: 文件大小，单位字节
      file_random_md5:
        type: string
        description: 文件的随机采样MD5
      file_random_md5_method:
        type: string
        description: 文件的随机采样MD5方法
      file_standard_md5:
        type: string
        description: 文件的标准MD5
      file_save_path:
        type: string
        description: 文件的保存路径
      chunk_size:
        type: integer
        description: 文件块大小，单位字节
      chunk_count:
        type: integer
        description: 文件块个数
      origin_file_name:
        type: string
        description: 原始文件名称
      uploading_chunk_list:
        type: string
        description: 正在上传的文件块编号Json列表
      uploaded_chunk_list:
        type: string
        description: 已完成上传的文件块编号Json列表
      shared_file_id:
        type: integer
        description: 共享目标文件ID
      last_sharing_time:
        type: string
        description: 上次被共享的时间
      chunk_merged:
        type: boolean
        description: 是否完成了文件块合并
      upload_spped:
        type: integer
        description: 文件上传的速度
      upload_end_time:
        type: string
        description: 文件上传结束的时间
      additional_time:
        type: integer
        description: 特殊场景下追加剩余时间用于返回正确的估计时间
      user_id:
        type: integer
        description: 所属用户ID
      usage_tag:
        type: string
        description: 文件的上传用途标签
      create_time:
        type: string
        description: 创建上传文件任务的时间
  UploadFileInfoList:
    type: object
    properties:
      code:
        type: integer
        description: 状态码
      message:
        type: string
        description: 状态信息
      list_size:
        type: integer
        description: 显示列表的元素总数
      data:
        type: array
        items:
          $ref: '#/definitions/UploadFileInfo'
  UploadFileInfoSingle:
    type: object
    properties:
      code:
        type: integer
        description: 状态码
      message:
        type: string
        description: 状态信息
      data:
        $ref: '#/definitions/UploadFileInfo'
  UploadStatus:
    type: object
    properties:
      progress:
        type: string
        description: 上传文件进度，0-100的浮点数
      upload_status:
        type: string
        description: 上传状态（显示文字）
      file_size:
        type: string
        description: 当前上传文件的大小，单位字节
      uploaded_data_size:
        type: string
        description: 已经上传的数据大小，单位字节
      left_upload_time:
        type: integer
        description: 剩余的上传时间，单位秒
      network_speed:
        type: integer
        description: 当前的上传速度，单位字节每秒
      upload_finished:
        type: boolean
        description: 上传流程是否可以结束，True表示可以结束
      upload_finished_status_code:
        type: integer
        description: 上传完成后的结束状态码，0表示正确完成
      upload_finished_status_msg:
        type: string
        description: 上传完成后显示的状态信息，错误/正确信息
  UploadFileFeedback:
    type: object
    properties:
      code:
        type: integer
        description: 状态码
      message:
        type: string
        description: 状态信息
      data:
        type: object
        properties:
          file_info:
            $ref: '#/definitions/UploadFileInfo'
          upload_status:
            $ref: '#/definitions/UploadStatus'
  UploadChunkInfo:
    type: object
    properties:
      id:
        type: integer
        description: 文件块ID
      chunk_offset:
        type: string
        description: 当前文件块在文件中的偏移量，单位字节
      chunk_size:
        type: string
        description: 文件块的实际大小，单位字节
      chunk_file_path:
        type: string
        description: 文件块的存储路径
      file_chunk_id:
        type: integer
        description: 文件块在文件内部的相对位置编号
      chunk_md5:
        type: string
        description: 文件块的md5
      file_id:
        type: integer
        description: 所属文件ID
      upload_breakpoint_offset:
        type: string
        description: 文件块的上传断点偏移量，块内偏移量，单位字节
      shared_chunk_id_list:
        type: string
        description: 共享文件块的ID列表
      upload_start_time:
        type: string
        description: 上传开始的时间
      upload_breakpoint_time:
        type: string
        description: 上传中断的时间
      upload_end_time:
        type: string
        description: 上传结束的时间
      chunk_progress_gap:
        type: string
        description: 单个文件块上传所占百分比
  UploadChunkFeedback:
    type: object
    properties:
      code:
        type: integer
        description: 状态码
      message:
        type: string
        description: 状态信息
      data:
        type: object
        properties:
          new_mission:
            $ref: '#/definitions/UploadChunkInfo'
          upload_status:
            $ref: '#/definitions/UploadStatus'
  DownloadFileInfo:
    type: object
    properties:
      id:
        type: integer
        description: 文件ID
      service_id:
        type: integer
        description: 创建该服务的ID
      file_size:
        type: integer
        description: 文件大小，单位字节
      src_file_name:
        type: string
        description: 下载源文件名称
      src_file_path:
        type: string
        description: 下载源文件的服务器绝对路径
      download_file_name:
        type: string
        description: 映射后下载文件名称
      download_file_path:
        type: string
        description: 映射后下载文件的服务器绝对路径
      static_download_file_path:
        type: string
        description: 映射后下载文件的静态文件相对路径
      user_id:
        type: integer
        description: 所属用户ID
      invalidated_time:
        type: string
        description: 下载文件的失效时间
      create_time:
        type: string
        description: 创建上传文件任务的时间
  DownloadFileInfoList:
    type: object
    properties:
      code:
        type: integer
        description: 状态码
      message:
        type: string
        description: 状态信息
      list_size:
        type: integer
        description: 显示列表的元素总数
      data:
        type: array
        items:
          $ref: '#/definitions/DownloadFileInfo'
  DownloadFileInfoSingle:
    type: object
    properties:
      code:
        type: integer
        description: 状态码
      message:
        type: string
        description: 状态信息
      data:
        $ref: '#/definitions/DownloadFileInfo'