IP:
  DATABASE: 192.168.9.64
  USER: 192.168.2.156:31151
  USER_DELETE: 192.168.9.64:33133
  K8S: 192.168.9.64:30887
  K8S_DIST: 192.168.9.64:33185
  NFS: 192.168.9.64
  IMAGE: 192.168.2.156:31152
  SERVICE_SHOP: 192.168.9.64:32295
  SAMPLE_SET: 192.168.9.64:28000

database:
  minconn: 5
  maxconn: 200
  user: iecas
  password: 123456
  dbname: geodl_iecas
  port: 32189
  cursor_factory: psycopg2.extras.DictCursor

user:
  usr_url: http://{}/api/v1/users/token_check
  usr_id_to_name: http://{}/api/v1/users/
  usr_get_infos: http://{}/api/v1/users/get
  usr_register: "{}"
  usr_delete: http://{}/airserver-2.0/user_delete_all_source

notebook:
  cpu: 1
  mem: 4
  gpu: 0
  work_dir: /home/airstudio
  user_id: 1000
  group_id: 100
  prefix: http://MASTER_IP:31173
  sendshowport: http://MASTER_IP:32186/components/generate_notebook/
  specific_user: 1839
  specific_imageid: 4

debug:
  default_user_name: airstudio
  cpu: 1
  mem: 4
  gpu: 1
  host_address: MASTER_IP

gateway:
  domain: http://MASTER_IP:31173

k8s:
  k8s_dist_create: http://{}/api/v1/airengine/distribution/
  k8s_create: http://{}/api/v1/airscheduler/task/
  k8s_start: http://{}/api/v1/airscheduler/task/{}/start
  k8s_stop: http://{}/api/v1/airscheduler/task/{}/stop
  k8s_delete: http://{}/api/v1/airscheduler/task/
  k8s_observe_object: http://{}/api/v1/airscheduler/task/{}

path:
    data_path: /var/nfs/general/data
    static_path: /static
    airpipeline_path: /airpipeline/base
    visual_path: /airpipeline/visual

status_monitor:
  monitor_delete_invaild_train_task: 30
  monitor_running_job: 10

job:
  work_dir: /app
  dataset_dir: /dataset
  model_dir: /data/model
  log_dir: /data/log

tag_dic:
  tensorflow: 0
  pytorch: 1
  single_algorithm: 100
  distributed_algorithm: 101
  model: 102
  image_classification: 200
  object_detection: 201
  image_segmentation: 202
  text_classification: 203
  sound_classification: 204
  video_classification: 205

role:
  admin: 0
  user: 1

app_config:
  host: 0.0.0.0
  port: 5000

image:
  default_notebook_image_id: 0
  image_get_info_url: http://{}/api/v1/images/get/{}
  image_build: http://{}/api/v1/images/build
  image_get_infos: http://{}/api/v1/images/get


service_shop:
  create_service: http://{}/api/v1/service

sample_set:
  id2path_url: http://{}/geoapi/V1/sampleset-platform/sampleset/condition/list?id={}&sampleSetClassification={}
  ids2infos: http://{}/geoapi/V1/sampleset-platform/sampleset/condition/list?&sampleSetIdList={}
