database:
  dbhost: 192.168.9.64
  minconn: 5
  maxconn: 200
  user: iecas
  password: 123456
  dbname: geodl_iecas
  port: 32189
  cursor_factory: psycopg2.extras.DictCursor

user:
  usr_url: http://192.168.2.156:31151/api/v1/users/token_check
  usr_id_to_name: http://192.168.2.156:31151/api/v1/users/
  usr_get_infos: http://192.168.2.156:31151/api/v1/users/get

notebook:
  cpu: 1
  mem: 4
  gpu: 0
  work_dir: /home/airstudio
  user_id: 1000
  group_id: 100
  prefix: http://MASTER_IP:31173
  sendshowport: http://MASTER_IP:32186/components/generate_notebook/
  specific_user: 1839
  specific_imageid: 4

debug:
  default_user_name: airstudio
  cpu: 1
  mem: 4
  gpu: 1
  host_address: MASTER_IP

gateway:
  domain: http://MASTER_IP:31173

k8s:
  k8s_dist_create: http://192.168.9.64:33185/api/v1/airengine/distribution/
  k8s_create: http://192.168.9.64:30887/api/v1/airscheduler/task/
  k8s_start: http://192.168.9.64:30887/api/v1/airscheduler/task/{}/start

pvc:
  prefix_path: /mnt/mfs

path:
  airStudio_path: /mnt/mfs/airstudio
  airPaas_path: /mnt/mfs/airpaas
  paas_dockerfile_path: /mnt/mfs/airpaas/service
  image_tmp: /mnt/mfs/image_tmp
  document_path: /mnt/mfs/data/static/assets/airstudio_pdf_manager
  static_path: http://192.168.9.64:31153/api/v1/static/assets/airstudio_pdf_manager
  airpipline_path: /var/nfs/general/airpipline_all_data
  visual_path: /var/nfs/general/airpipline_all_visual/logs

datasetpath:
  path: /mnt/mfs/data

status_monitor:
  monitor_step_time: 5

job:
  work_dir: /app
  dataset_dir: /dataset
  model_dir: /data/model
  log_dir: /data/log

tag_dic:
  tensorflow: 0
  pytorch: 1
  single_algorithm: 100
  distributed_algorithm: 101
  model: 102
  image_classification: 200
  object_detection: 201
  image_segmentation: 202
  text_classification: 203
  sound_classification: 204
  video_classification: 205

role:
  admin: 0
  user: 1

app_config:
  host: 0.0.0.0
  port: 5000

image:
  default_notebook_image_id: 0
  image_get_info_url: http://192.168.2.156:31152/api/v1/images/get/{}
  image_build: http://192.168.2.156:31152/api/v1/images/build
  image_get_infos: http://192.168.2.156:31152/api/v1/images/get


service_shop:
  create_service: http://192.168.9.64:32295/service

sample_set:
  prefix: /mnt/mfs/data
  id2path_url: http://192.168.9.64:28000/geoapi/V1/sampleset-platform/sampleset/condition/list?id={}&sampleSetClassification={}

static_path:
  prefix_path: /var/nfs/general/data/static/
