database:
    dbhost: 192.168.9.64
    minconn: 5
    maxconnL: 200
    user: iecas
    password: 123456
    dbname: geodl_iecas
    port: 32189
    cursor_factory: psycopg2.extras.DictCursor

user:
    usr_url: http://192.168.2.156:31151/api/v1/users/token_check

notebook:
    cpu: 1
    mem: 4
    gpu: 0
    work_dir: /home/airstudio
    user_id: 1000
    group_id: 100
    prefix: http://MASTER_IP:31173
    sendshowport: http://MASTER_IP:32186/components/generate_notebook/
    specific_user: 1839
    specific_imageid: 4

debug:
    default_user_name: airstudio
    cpu: 1
    mem: 4
    gpu: 1
    host_address: MASTER_IP

gateway: 
    domain: http://MASTER_IP:31173

k8s: 
    k8s_dist_create: http://192.168.9.64:33185/api/v1/airengine/distribution/
    k8s_create: http://192.168.9.64:30887/api/v1/airscheduler/task/

pvc: 
    prefix_path: /mnt/mfs

path:
    airStudio_path: /mnt/mfs/airstudio
    airPaas_path: /mnt/mfs/airpaas
    paas_dockerfile_path: /mnt/mfs/airpaas/service
    image_tmp: /mnt/mfs/image_tmp
    document_path: /mnt/mfs/data/static/assets/airstudio_pdf_manager
    static_path: http://192.168.9.64:31153/api/v1/static/assets/airstudio_pdf_manager
    airpipline_path: /mnt/mfs/airpipline_all_data

datasetpath: 
    path: /mnt/mfs/data

tab_name: 
    traincodetab: traincodetab
    usertab: usertab
    aienginetab: aienginetab
    paasservicetab: paasservicetab
    smoketesttab: smoketesttab
    modeltab: modeltab

job: 
    work_dir: /app
    dataset_dir: /dataset
    model_dir: /data/model
    log_dir: /data/log

token: 
    secret: abc123
    min_time: 18000
    max_time: 36000

hub: 
    prefix: www.registry.cyber.ai
    user: admin
    password: Harbor12345
    protocol: http
    airstudio_pro: airproject

redis: 
    host: MASTER_IP
    password:
    port: 31171
    db: 0

paas_service: 
    namespace: airpaas
    smoke_namespace: smokepaas
    work_dir: /app

intelligent_platform: 
    url: http://MASTER_IP:32295/service
    job_url: http://MASTER_IP:32295/service
    update_url: http://MASTER_IP:32295/service/

edge_platform: 
    upload_url: http://173.21.8.26:8002/api/modelSimplify/fileUpload

status_dic: 
    creating: 0
    create_failed: 1
    running: 2
    run_failed: 3
    terminated: 4
    ready: 100
    finished: 200
    to_audit: 300
    audit_not_approved: 301
    pass_the_audit: 302

tag_dic: 
    tensorflow: 0
    pytorch: 1
    single_algorithm: 100
    distributed_algorithm: 101
    model: 102
    image_classification: 200
    object_detection: 201
    image_segmentation: 202
    text_classification: 203
    sound_classification: 204
    video_classification: 205

role: 
    admin: 0
    user: 1

app_config: 
    host: 0.0.0.0
    port: 5000

image: 
    default_notebook_image_id: 0
    image_get_info_url: http://192.168.2.156:31152/api/v1/images/get/{}